### PR TITLE
protect overflow when computing expiration

### LINKED ISSUE #52: [BUG] overflow when ttl is large
The following panics:

```rust
#[tokio::test]
async fn large_ttl() {
    let cache: moka::future::Cache<(), ()> = moka::future::CacheBuilder::new(usize::MAX)
        .time_to_live(Duration::MAX)
        .build();
    cache.insert((), ()).await;
    cache.sync();
}
```

```
panicked at 'overflow when adding duration to instant',
.cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.9.3/src/instant.rs:142:14
```

### PR DESCRIPTION
**Pull request by barkanido**
This change protects against overflow using 2 measures:
1. cache builders now won't build caches with time_tolive or
time_to_idle higher than 1000 years.
2. for future  computations, the internal Instant type will now only
allow checked additions to force handling a possible overflow. in
addition, an overflow is now an explicit panic instead of a silent
overflow.

closes #52

### CODE REVIEW

**Comment by barkanido** [comment]
@tatsuya6502 can you help here?

`cargo build --no-default-features --features future`

fails here since the new code is located at `common/time_atomic64.rs`, which is not compiled when `--no-default-features` I have done this before noticing the `"atomic64"` feature flag, and because `Instant` was already there. WDYT? should I move it? how to go around this?

**Comment by tatsuya6502** [comment]
> how to go around this?

The `"atomic64"` feature is used to select the source file for the `time` module. Some 32-bit platforms (MIPS and ARMv5) do not support `AtomicU64` and some older versions of quanta crate will not compile. So Moka has two different implementations for `time`:

https://github.com/moka-rs/moka/blob/107408208e3e91472e5cae2f9a6c37ae02acddbf/src/common.rs#L7-L13

However, by a [historical reason](https://github.com/moka-rs/moka/commit/107408208e3e91472e5cae2f9a6c37ae02acddbf), these two source files (`common/time_atomic64.rs` and `common/time_compat.rs`) now have identical definitions for the following types:

```rust
pub(crate) type Instant = quanta::Instant;
pub(crate) type Clock = quanta::Clock;

#[cfg(test)]
pub(crate) type Mock = quanta::Mock;
```

Let's clean them up now. You can remove them from these source files, and put them to `common.rs`.

**Comment by tatsuya6502** [comment]
> You can remove them from these source files, and put them to `common.rs`.

Or maybe rename the current `time` module to something else (e.g. `atomic_time`).

```diff
  #[cfg_attr(feature = "atomic64", path = "common/time_atomic64.rs")] 
  #[cfg_attr(not(feature = "atomic64"), path = "common/time_compat.rs")] 
- pub(crate) mod time;
+ pub(crate) mod atomic_time;
```

and delete `Instant` and `Clock` and `Mock` from these file.

Then create `common/time.rs` and put them.

**Comment by tatsuya6502** [comment]
For the Rustfmt warnings, please do the followings:

1. Make sure you have the latest stable version of Rust installed. (e.g. Run `rustup update stable`)
    - You will use Rust stable because Moka's GitHub Actions uses Rust stable for Rustfmt check.
2. At the package root directory (where `Cargo.toml` is stored), run `cargo fmt`.
    - This will reformat all Rust source files in the package.
3. Run `cargo fmt -- --check; echo $?` to verify code is formatted.
    - If code is formatted, it will only print the exit code `0`, otherwise it will print diffs and then the exit code `1`.

**Review by tatsuya6502 — APPROVED** [review]
LGTM. Thanks a lot for your contribution!

I will take care of the Rustfmt diffs after merging.

**Comment by tatsuya6502** [comment]
Hi @barkanido, I noticed you are not on our [contributors page](https://github.com/moka-rs/moka/graphs/contributors). I wish everybody who contributed to this project should be on the page to get some credits.

I think this is because GitHub cannot locate your account from the email address used by your commits. As you can see, your name is not clickable on the list of your commits [here](https://github.com/moka-rs/moka/pull/56/commits), but my name (GitHub user name) is clickable on my commits [here](https://github.com/moka-rs/moka/pull/58/commits).

I think you will need to go to GitHub's [settings -> email page](https://github.com/settings/emails), and add your email address there if you have not.

Thanks!

**Comment by barkanido** [comment]
done. Thanks @tatsuya6502 the commits are now clickable. the contributors' page is still not updated though. maybe it take time, idk.

**Comment by tatsuya6502** [comment]
Hi @barkanido, Thanks for updating your setting. I wrote to the GitHub support and told that the contributors' page was not updated. They fixed the problem by re-indexing the data. Now you are on the page!

From the GitHub support:
> I have reindexed the Insight contributor's graph for the repository and the contributor's list now display correctly.
>
> https://github.com/moka-rs/moka/graphs/contributors
> 
> Hope this helps!

**Pull request merged**
