### PR TITLE
Add 'by_ref' api

### PR DESCRIPTION
**Pull request by LMJW**
Related issue #185 

Add "by_ref" version of api for "get_with", "get_with_if", "try_get_with", "optionally_get_with"

### CODE REVIEW

**Comment by LMJW** [comment]
CI failure.
```
thread 'sync::cache::tests::test_key_lock_used_by_immediate_removal_notifications' panicked at 'assertion failed: `(left == right)`
  left: `Invalidate("a2")`,
 right: `EndNotify("a0", Expired)`: expected[4]', src/sync/cache.rs:3811:13
```

This might not related to the change

**Review by tatsuya6502 — APPROVED** [review]
LGTM. Thank you!

I will run pre-release tests tonight (UTC+0800), and if it goes well, I will release [v0.9.5](https://github.com/moka-rs/moka/milestone/27?closed=1).

Just FYI, I will probably hide (comment out) `get_with_if_by_ref` for v0.9.5. I am planing to deprecate `get_with_if` once the `entry`/`entry_by_ref` API are ready (v0.10.0?). The same functionality to `get_with_if` will be provided via `entry*` APIs. I would like to avoid adding `get_with_if_by_ref` and then deprecating immediately. I will not remove your code but comment out as we can use it in the `entry*` APIs.

**Comment by LMJW** [comment]
Thanks for approving the PR. If I knew it would be deperacated, I would probably not add the new api for the deprecated function. No worries. You can remove it if it is not needed :)

**Comment by tatsuya6502** [comment]
OK. All tests passed and I published [v0.9.5](https://crates.io/crates/moka/0.9.5) to crates.io. You will see [`optionally_get_with_by_ref`](https://docs.rs/moka/latest/moka/sync/struct.Cache.html#method.optionally_get_with_by_ref) in the doc.

Thanks for your contribution!

**Comment by LMJW** [comment]
Nice! Thanks for your review. :)

**Pull request merged**
